#Simple test particle for effective area
/run/initialize
/gps/position 0.0 0.0 -20.0 cm
/gps/direction 0 0 1
/gps/energy 1 keV
/gps/particle gamma
/gps/pos/type Beam
/gps/pos/shape Circle 
/gps/pos/radius 7 cm
/gps/source/list
/World/SetWorldMaterial Vaccum
/run/beamOn 10000

/gps/energy 100 keV
/run/beamOn 10000

/gps/energy 200 keV
/run/beamOn 10000

/gps/energy 300 keV
/run/beamOn 10000

/gps/energy 400 keV
/run/beamOn 10000

/gps/energy 500 keV
/run/beamOn 10000
