#Transmission Simulation data to compare with real
/run/initialize
/gps/position 0.0 0.0 -20.0 cm
/gps/direction 0 0 1
/gps/energy 30.85 keV
/gps/particle gamma
/gps/pos/type Beam
/gps/pos/shape Circle 
/gps/pos/radius 7 cm
/gps/source/list
/World/SetWorldMaterial Vacuum
/run/beamOn 100000

/gps/energy 81.00 keV
/run/beamOn 100000

/gps/energy 22.10 keV
/run/beamOn 100000

/gps/energy 25.00 keV
/run/beamOn 100000
